kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi
nodes:
- role: worker
- role: worker
- role: worker
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 8082
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    listenAddress: "0.0.0.0"
    hostPort: 4443
    protocol: TCP