GET http://localhost:3344

### get-post
POST http://localhost:3344/addUser

### post-body urlencoded
POST http://localhost:3344/echoPost
Content-Type: application/x-www-form-urlencoded

campo1=v1&fecha=12-4-2014&edad=10

### post-body json
POST http://localhost:3344/echoPost
Content-Type: application/json

{"campo1":"v1","fecha":"12-4-2014","edad":10}

### post-body urlencoded extended
POST http://localhost:3344/echoPost
Content-Type: application/x-www-form-urlencoded

a=1&a=2&a=3&person[name]=jose&persona[age]=45

### query-string
POST http://localhost:3344/echoPost?a=1&b=2&c=3&c=5&c=3
Content-Type: application/x-www-form-urlencoded

a=1&a=2&a=3&person[name]=jose&persona[age]=45

### params post
POST http://localhost:3344/echoParamsPost/222/facturas/2535
Content-Type: application/x-www-form-urlencoded

a=1&a=2&a=3&person[name]=jose&persona[age]=45

### params post
GET http://localhost:3344/echoParamsGet/222/facturas/2535?a=1&b=2&c=3&c=5&c=3

### ficheros-estaticos
GET http://localhost:3344/p1.html

### ficheros-estaticos docs
GET http://localhost:3344/docs

### minio crear bucket
POST http://localhost:3344/minio/createBucket
Content-Type: application/json

{"nombre":"curso"}

### minio borrar fichero
DELETE  http://localhost:3344/minio/curso/app.ts